# Generated by Django 4.1.7 on 2023-03-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(null=True)),
                ('upload_image', models.ImageField(null=True, upload_to='image_uploads/')),
                ('upload_id_proof', models.FileField(null=True, upload_to='ID_proof_uploads/')),
                ('contact_no', models.CharField(max_length=12, null=True)),
                ('address', models.CharField(max_length=25, null=True)),
                ('work_exp', models.CharField(max_length=12, null=True)),
                ('work_field', models.CharField(choices=[('manager', 'manager'), ('account', 'account'), ('billing', 'billing'), ('sales', 'sales'), ('custom', 'custom')], max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
