# Generated by Django 4.1.7 on 2023-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_data_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='access_token',
            field=models.CharField(choices=[('manager', 'manager'), ('account', 'account'), ('Custodian', 'Custodian'), ('Packer', 'Packer'), ('Farm laborer', 'Farm laborer'), ('Gardener', 'Gardener'), ('Production worker', 'Production worker'), ('Forklift operator', 'Forklift operator'), ('Landscape technician', 'Landscape technician'), ('Package handler', 'Package handler')], max_length=1000, null=True),
        ),
    ]
