# Generated by Django 4.1.7 on 2023-03-21 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_data_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='access_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
