# Generated by Django 4.1.7 on 2023-03-21 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_data_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='access_token',
        ),
    ]
