# Generated by Django 4.1.7 on 2023-03-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_user_data_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='work_field',
            field=models.CharField(choices=[('manager', 'manager'), ('account', 'account'), ('Customer', 'Customer'), ('Packer', 'Packer'), ('Farm laborer', 'Farm laborer'), ('Gardener', 'Gardener'), ('Production worker', 'Production worker'), ('Forklift operator', 'Forklift operator'), ('Landscape technician', 'Landscape technician'), ('Package handler', 'Package handler')], max_length=50, null=True),
        ),
    ]
