# Generated by Django 4.1.7 on 2023-03-24 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_remove_user_data_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='work_field',
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_field', models.CharField(choices=[('Packer', 'Packer'), ('Farm laborer', 'Farm laborer'), ('Gardener', 'Gardener'), ('Production worker', 'Production worker'), ('Forklift operator', 'Forklift operator'), ('Landscape technician', 'Landscape technician'), ('Package handler', 'Package handler')], max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
