# Generated by Django 4.1.7 on 2023-04-04 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_serviceprovider_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='contact_no',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Contact Field must contain only 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only alphabetical characters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='last_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only alphabetical characters.', regex='^[a-zA-Z]+$')]),
        ),
    ]
