# Generated by Django 4.1.7 on 2023-03-21 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userfeedback_ratings1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='ratings1',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
