# Generated by Django 4.1.7 on 2023-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userfeedback_ratings1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidforjob',
            name='job_biding_price',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bidforjob',
            name='job_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidforjob',
            name='job_payment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
