# Generated by Django 4.1.7 on 2023-03-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bidforjob_job_biding_price_bidforjob_job_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidforjob',
            name='job_payment',
        ),
    ]
