# Generated by Django 4.1.7 on 2023-03-22 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_bidforjob_job_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
