# Generated by Django 4.1.7 on 2023-03-24 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0010_remove_user_data_work_field_serviceprovider'),
        ('app', '0010_alter_job_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidforjob',
            name='bid_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='bidforjob',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.serviceprovider'),
        ),
    ]
