# Generated by Django 4.1.7 on 2023-03-24 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_bidforjob_bid_date_bidforjob_service_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidforjob',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
