# Generated by Django 4.1.7 on 2023-03-24 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bidforjob_user_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidforjob',
            name='bid_date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
