# Generated by Django 4.1.7 on 2023-03-31 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_userfeedback_service_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidforjob',
            name='job_biding_price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
