# Generated by Django 4.1.7 on 2023-04-03 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_bidforjob_job_biding_price_alter_job_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='ratings',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
