# Generated by Django 4.1.7 on 2023-04-03 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_serviceprovider_ratings'),
        ('app', '0018_alter_bidforjob_job_alter_bidforjob_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidforjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
        migrations.AlterField(
            model_name='bidforjob',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.serviceprovider'),
        ),
    ]
