# Generated by Django 4.1.7 on 2023-04-04 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_bidforjob_job_alter_bidforjob_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only alphabetical characters.', regex='^[a-zA-Z]+$')]),
        ),
    ]
