# Generated by Django 4.1.7 on 2023-04-04 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_job_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only digits', regex='^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='pin_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only digits', regex='^\\d{1,10}$')]),
        ),
    ]
