# Generated by Django 4.1.7 on 2023-04-04 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_job_contact_alter_job_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Field must contain only digits', regex='^\\d{10}$')]),
        ),
    ]
