# Generated by Django 4.1.7 on 2023-04-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_job_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_field', message='Contact Field must contain only 10 digits', regex='^\\d{10}$')]),
        ),
    ]
